### PR TITLE
Add railgun cannons

### PR DESCRIPTION
**Pull request by kiedtl**
Currently, they're just referred to as purple and blue cannons. In a future PR I'd like to give them actual names, possibly doing the same for the other cannons (naming them "hvy./med./lgt. beam cannon" or similar).

The textures for the new cannons and railgun slugs are also fairly unoriginal; if no-one else more skilled with texture-making shows interest in creating better textures, I'll try my best to do so (in a separate PR).

### CODE REVIEW

**Comment by kiedtl** [comment]
One note: to differentiate the railguns a bit more from the green one, I decreased the green's speed by 2 (10 -> 8) and set the railgun and helical railgun to 9 and 10 speed, respectively. Unfortunately it seems that setting the speed higher than 10 causes the entity to travel multiple nodes at a time, thus occasionally clipping through targets and having no effect.

**Comment by kiedtl** [comment]
Could you elaborate? I've tried to keep the existing cannon's behaviour as close to the original as possible.

Here are the changes that I've deliberately made:

- Cannons don't interact with item entities. Previously hitting one would trigger the explosion. (In any case, this behavior wouldn't work for railguns, since it'd stop penetration early.)
- As noted, the speed is decreased, but it seems a fairly minor change. I'm curious how this would break a build.

**Comment by kiedtl** [comment]
Marked as draft since I realized I had forgotten to test digilines, but reviews still appreciated in the meantime.

**Comment by S-S-X** [comment]
I do like that this would make uranium0_ingot bit more useful 👍

**Comment by BuckarooBanzay** [comment]
nice work :+1: there are some issues (rotated away inventory image, not connecting hv to the side, missing description) but they were there before, so :shrug:

**Comment by kiedtl** [comment]
I'm curious what you mean by 'missing description' -- all the cannons have a "description" in the node name. Is there another place for node descriptions that I'm missing?

Hm, it would be nice to see that description the HUD now that I've come to think of it.

**Pull request merged**
